### ISSUE TITLE
Celery 4.0

### ISSUE THREAD

**Issue by perrohunter** [maciej-gol/tenant-schemas-celery#10]
Are there any plans to support celery 4.0?

**Comment by maciej-gol** [comment]
I'll check the compatibility with the newest tenant-schemas and celery
within a week.

6 mar 2017 20:11 "perrohunter" <notifications@github.com> napisał(a):

**Comment by perrohunter** [comment]
thanks for the prompt reply

I found a workaround to get this library to work with Celery 4.0

Turns out Celery 4.0 checks the `kwargs` being passed and throws an error if there's any it doesn't like, by changing the task notation to `@app.task(typing=False)` everything seems to work again.

Seems like the fix would be to get celery's task to accept this unknow parameter

```
@app.task(typing=False)
def mytasl(bla,ble, bli=None):
   pass
```

**Comment by perrohunter** [comment]
The original error I was getting was

```
TypeError: model_event() got an unexpected keyword argument '_schema_name'
```

**Comment by maciej-gol** [comment]
Either this, or `@task` could actually return a function that wraps the
original one and accepts the kwarg. Will look into it.

6 mar 2017 20:28 "perrohunter" <notifications@github.com> napisał(a):

**Comment by maciej-gol** [comment]
@perrohunter could you check whether the `[celery_4](https://github.com/maciej-gol/tenant-schemas-celery/tree/celery_4)` branch works for you?

**Comment by alex-bes** [comment]
Hey guys! any luck with testing this? @perrohunter @maciej-gol

**Comment by maciej-gol** [comment]
Sorry, will merge it today.

4 kwi 2017 09:54 "Alexander Beskrovny" <notifications@github.com>
napisał(a):

**Comment by alex-bes** [comment]
@maciej-gol thanks!

**Comment by maciej-gol** [comment]
@alex-bes the `0.1.6` version should be in the index now.
